spring:
  application:
    name: fraud-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fraud-service
      auto-offset-reset: earliest

server:
  port: 8081

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"