package dev.jkiakumbo.paymentorchestrator.orchestratorservice.state

enum class PaymentState {
    INITIATED,
    FRAUD_CHECK_PENDING,
    FRAUD_CHECK_COMPLETED,
    FRAUD_CHECK_FAILED,
    FUNDS_RESERVATION_PENDING,
    FUNDS_RESERVED,
    FUNDS_RESERVATION_FAILED,
    PROCESSOR_EXECUTION_PENDING,
    PROCESSOR_EXECUTED,
    PROCESSOR_EXECUTION_FAILED,
    LEDGER_UPDATE_PENDING,
    LEDGER_UPDATE_FAILED,
    COMPLETED,
    FAILED,
    COMPENSATING,
    COMPENSATED
}