package dev.jkiakumbo.paymentorchestrator.state

enum class PaymentState {
    INITIATED,
    FRAUD_CHECK_PENDING,
    FRAUD_CHECK_COMPLETED,
    FRAUD_CHECK_FAILED,
    FUNDS_RESERVATION_PENDING,
    FUNDS_RESERVED,
    FUNDS_RESERVATION_FAILED,
    PROCESSOR_EXECUTION_PENDING,
    PROCESSOR_EXECUTED,
    PROCESSOR_EXECUTION_FAILED,
    LEDGER_UPDATE_PENDING,
    LEDGER_UPDATE_FAILED,
    COMPLETED,
    FAILED,
    COMPENSATING,
    COMPENSATED
}

enum class PaymentEvent {
    FRAUD_CHECK_REQUESTED,
    FRAUD_CHECK_APPROVED,
    FRAUD_CHECK_DECLINED,
    FUNDS_RESERVATION_REQUESTED,
    FUNDS_RESERVED,
    FUNDS_RESERVATION_FAILED,
    PROCESSOR_EXECUTION_REQUESTED,
    PROCESSOR_EXECUTED,
    PROCESSOR_EXECUTION_FAILED,
    LEDGER_UPDATE_REQUESTED,
    LEDGER_UPDATED,
    LEDGER_UPDATE_FAILED,
    COMPENSATION_TRIGGERED,
    COMPENSATION_COMPLETED
}